### ISSUE TITLE
histogram.txt on release to allow LCD Smartie get info about dll usage

### ISSUE THREAD

**Issue by limbo666** [lucassiglo21/Histogram-plugin-for-LCD-Smartie#1]
The latest LCD Smartie is able to read info from dll and external txt files and display it on plugin pane. 
Adding a text file on the release package should give a better user experience.
![image](https://github.com/user-attachments/assets/cbe7ce58-0a18-4fc9-9096-59ca437dedd4)

Compatible file is here:
[histogram.txt](https://github.com/user-attachments/files/17717057/histogram.txt)

**Comment by lucassiglo21** [comment]
Thank you!, i just added the file to the release
